[package]
name = "barber"
version = "0.1.0"
authors = ["J/A <archer884@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazycell = "1.2"
sha2 = "0.8"
structopt = "0.2"
walkdir = "2.2"
